# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ARSocialPhotoApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
    pod 'Firebase/Core'
    pod 'Firebase/Firestore'
    pod 'Firebase/Storage'
    pod 'Firebase/Auth'
    pod 'FirebaseUI/Firestore'
    pod 'FirebaseUI/Storage'
    pod 'FirebaseUI/Auth'
    pod 'FirebaseUI/Google'

  # Pods for ARSocialPhotoApp

end
